load(":defs.bzl", "c_test", "c_tests_for_runtime")
load("//tools:conformance.bzl", "wasi_manifest", "wasi_suite")

_WASI_C = wasi_manifest(
    name = "WASI C tests",
    version = "wasm32-wasip1",
    labels = ["c-wasip1"],
)

_C_TESTS = [
    c_test("clock_getres-monotonic"),
    c_test("clock_getres-realtime"),
    c_test("clock_gettime-monotonic"),
    c_test("clock_gettime-realtime"),
    c_test("fopen-with-no-access"),
    c_test("sock_shutdown-invalid_fd"),
    c_test("sock_shutdown-not_sock"),
    c_test("lseek"),
    c_test("fdopendir-with-access"),
    c_test("fopen-with-access"),
    c_test("pread-with-access"),
    c_test("pwrite-with-access"),
    c_test("pwrite-with-append"),
    c_test("stat-dev-ino"),
]

_WASMTIME_TESTS = c_tests_for_runtime(
    tests = _C_TESTS,
    name = "wasmtime",
    runtime = "toolchains//:wasmtime_runtime",
    manifest = _WASI_C,
)

wasi_suite(
    name = "wasmtime",
    tests = _WASMTIME_TESTS,
    visibility = ["//tests/..."],
)
