export_file(
    name = "wasmtime.py",
    src = "wasmtime.py",
    visibility = [
        "toolchains//...",
        "//tests/...",
    ],
)

filegroup(
    name = "dist_files",
    srcs = glob(["*.py"]),
    out = "adapters",
    copy = True,
    visibility = ["//tests/..."],
)
