version = 1

[[suite]]
name = "WASI Rust tests [wasm32-wasip1]"

# wasmtime's `fd_renumber` is buggy right now
[[suite.test]]
name = "renumber"
action = "skip"

# wasmtime's `fd_renumber` is buggy right now
[[suite.test]]
name = "stdio"
action = "skip"

[[suite]]
name = "WASI Rust tests [wasm32-wasip3]"