load(":defs.bzl", "asc_test", "asc_tests_for_runtime")
load("//tools:conformance.bzl", "wasi_manifest", "wasi_suite")

_WASI_ASSEMBLYSCRIPT = wasi_manifest(
    name = "WASI AssemblyScript tests",
    version = "wasm32-wasip1",
    labels = ["assemblyscript-wasip1"],
)

_ASSEMBLYSCRIPT_TESTS = [
    asc_test("args_sizes_get-no-arguments"),
    asc_test("environ_sizes_get-no-variables"),
    asc_test("fd_write-to-invalid-fd"),
    asc_test("proc_exit-success"),
    asc_test("random_get-non-zero-length"),
    asc_test("random_get-zero-length"),
    asc_test("args_get-multiple-arguments"),
    asc_test("args_sizes_get-multiple-arguments"),
    asc_test("environ_get-multiple-variables"),
    asc_test("environ_sizes_get-multiple-variables"),
    asc_test("fd_write-to-stdout"),
    asc_test("proc_exit-failure"),
]

_WASMTIME_TESTS = asc_tests_for_runtime(
    tests = _ASSEMBLYSCRIPT_TESTS,
    name = "wasmtime",
    runtime = "toolchains//:wasmtime_runtime",
    manifest = _WASI_ASSEMBLYSCRIPT,
)

wasi_suite(
    name = "wasmtime",
    tests = _WASMTIME_TESTS,
    visibility = ["//tests/..."],
)
