python_library(
    name = "wasi_test_runner",
    srcs = glob(["wasi_test_runner/**/*.py"]),
    base_module = "",
    visibility = ["//tools/..."],
    deps = [
        "//third-party/python:colorama",
        "//third-party/python:requests",
    ]
)

filegroup(
    name = "dist_files",
    srcs = glob(["wasi_test_runner/**/*.py"]) + [
        "requirements.txt",
        "requirements/common.txt",
        "requirements/prod.txt",
    ],
    out = "test-runner",
    copy = True,
    visibility = ["//tests/..."],
)
