python_binary(
    name = "run_wasi_test",
    main = "run_wasi_test.py",
    base_module = "",
    deps = ["//test-runner:wasi_test_runner"],
    visibility = ["//tests/..."],
)

python_binary(
    name = "package_dist",
    main = "package_dist.py",
    visibility = ["//tests/..."],
)
